- name: Creates a Identity Source in IBM Cloud Identity Cloud Directory. 
  ci:
    appliance:      "{{ inventory_hostname }}"
    client_id:      "{{ client_id }}"
    client_secret:  "{{ client_secret }}"
    lmi_port:       "{{ lmi_port }}"
    log:            "{{ log_level }}"
    force:          "{{ force }}"
    # header:         "application/scim+json"
    ciapi:
      sourcetypeid:   "{{ sourcetypeid }}"
      instancename:   "{{ instancename }}"
      new_instancename: "{{ new_instancename | default(None) }}"
      enabled:        "{{ enabled }}"
      properties:     "{{ properties }}"
    action: ibmsecurity.ci.configuration.identitysources.add