---
# THIS PLAYBOOK MUST BE RUN FROM CLI
- name: Check if Python module is installed
  hosts: "{{ hosts | default('all') }}"
  connection: local
  become: yes
  gather_facts: no
  tasks:   
    - command: "{{ ansible_python_interpreter | default('/usr/bin/python3') }} -c 'import {{ module }}; print({{ module }})'"
      vars:
        module: ibmsecurity
      register: test
    - debug:
        var: test.stdout

    - command: "{{ ansible_python_interpreter | default('/usr/bin/python3') }} -c 'import {{ module }}; print({{ module }})'"
      vars:
        module: tower_cli
      register: test
    - debug:
        var: test.stdout