- name: Update - Security - Authentication Factors - QR Code Login Configuration
  ci:
    appliance:      "{{ inventory_hostname }}"
    client_id:      "{{ client_id }}"
    client_secret:  "{{ client_secret }}"
    lmi_port:       "{{ lmi_port }}"
    log:            "{{ log_level }}"
    force:          "{{ force }}"
    # header:         "application/scim+json"
    ciapi:
      lsi_charset: "{{ lsi_charset }}"
      lsi_length:  "{{ lsi_length }}"
      dsi_charset: "{{ dsi_charset }}"
      dsi_length:  "{{ dsi_length }}"
      expiry:      "{{ expiry }}"
      enabled:     "{{ enabled }}"
    action: ibmsecurity.ci.security.authentication_factors.update_qr

