tower_host                            : "127.0.0.1:8043"
tower_username                        : "admin"
tower_password                        : "{{ vault_awx_password_secret }}"
tower_verify_ssl                      : False
tower_oauthtoken                      : "{{ vault_awx_oauthtoken }}"