- name: Add tower job template workflow
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Create tower job templatew workflow
      tower_workflow_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        # allow_simultaneous:           "{{ workflow.allow_simultaneous | default('no') }}"
        # ask_extra_vars:               "{{ workflow.ask_extra_vars | default('no') }}"
        # ask_inventory:                "{{ workflow.ask_inventory | default('no') }}"
        description:                  "{{ workflow.description | default('Created using Ansible Role') }}"
        # extra_vars:                   "{{ workflow.extra_vars | default(omit) }}"
        inventory:                    Brand 01
        # name:                         "{{ workflow.name }}"
        name:                         Workflow Template
        organization:                 Default
        # state:                        "{{ workflow.state | default('present') }}"
        # survey:                       "{{ workflow.survey | default(omit) }}"
        # survey_enabled:               "{{ workflow.survey_enabled | default('no') }}"        
        # schema: "{{ lookup('file', 'awx_add_job_template_workflow_schema.yml') }}"
        schema:
          - job_template: Demo Job Template
        
