
- name: Add tower job template
  hosts: "{{ hosts | default('all') }}"
  gather_facts: false
  connection: local
  tasks:
    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - add application"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/add_application.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - add application entitlements"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/add_application_entitlements.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - add attribute"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/add_attribute.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - add certificates"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/add_certificates.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - add group"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/add_group.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - add identitysource"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/add_identitysource.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - add personalcert"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/add_personalcert.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - add signercert"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/add_signercert.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - add user"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/add_user.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - add user to group"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/add_user_to_group.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - delete application"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/delete_application.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - delete attribute"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/delete_attribute.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - delete customization reset"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/delete_customization_reset.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - get all accesspolicies"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/get_all_accesspolicies.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - get all applications"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/get_all_applications.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - get all attributes"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/get_all_attributes.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - get all certificates"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/get_all_certificates.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - get all groups"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/get_all_groups.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - get all headernames group"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/get_all_headernames_group.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - get all headernames user"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/get_all_headernames_user.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - get all identitysources"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/get_all_identitysources.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - get all users"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/get_all_users.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - get customization download"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/get_customization_download.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - get group filter"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/get_group_filter.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - get user filter"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/get_user_filter.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - install python modules"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/install_python_modules.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - update authentication factos properties"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/update_authentication_factos_properties.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - upload customization page"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/upload_customization_page.yml"
        become_enabled: yes
        state: "present"

    - name: Create tower job template
      tower_job_template:      
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "CIC - upload customization zip"
        # description:
        job_type: "run"
        inventory: "AWX-localhost"
        project: "ibmsecurity_ci (master)"
        playbook: "ci-ansible-playbook-sample/upload_customization_zip.yml"
        become_enabled: yes
        state: "present"

