---
- job_template: CIC - add application
  failure:
  - inventory_source: Brand 01
  success:
  - project: ibmsecurity_ci (master)
    always:
    - job_template: CIC - add application awx
      success:
      - job_template: CIC - add application bookmark
