- name: Update Settings
  hosts: all
  gather_facts: false
  connection: local
  tasks:
        # tower_host:       --> see inventory
        # tower_username:   --> see inventory
        # tower_password:   --> see inventory
        # tower_verify_ssl: --> see inventory
        # tower_oauthtoken: --> see inventory

    # - name: Set the value of AWX_PROOT_BASE_PATH
    #   tower_settings:
    #     name: AWX_PROOT_BASE_PATH
    #     value: "/tmp"
    #   register: testing_settings

    # - name: Set the value of AWX_PROOT_SHOW_PATHS
    #   tower_settings:
    #     name: "AWX_PROOT_SHOW_PATHS"
    #     value: "'/var/lib/awx/projects/', '/tmp'"
    #   register: testing_settings

    # - name: Set the LDAP Auth Bind Password
    #   tower_settings:
    #     name: "AUTH_LDAP_BIND_PASSWORD"
    #     value: "Password"
    #   no_log: true

    # - name: Set all the LDAP Auth Bind Params
    #   tower_settings:
    #     settings:
    #       AUTH_LDAP_BIND_PASSWORD: "password"
    #       AUTH_LDAP_USER_ATTR_MAP:
    #         email: "mail"
    #         first_name: "givenName"
    #         last_name: "surname"        
    
    - name: Set SOCIAL_AUTH_SAML_SP_ENTITY_ID
      tower_settings:
        name: "SOCIAL_AUTH_SAML_SP_ENTITY_ID"
        value: "awx.domain.nl"
      no_log: true

# options: #######################################################################        

    # name:
    #   description:
    #     - Name of setting to modify
    #   required: False
    #   type: str

    # value:
    #   description:
    #     - Value to be modified for given setting.
    #   required: False
    #   type: str
    
    # settings:
    #   description:
    #     - A data structure to be sent into the settings endpoint
    #   required: False
    #   type: dict
    #   version_added: "3.7"
    
    # tower_oauthtoken:
    #   description:
    #     - The Tower OAuth token to use.
    #   required: False
    #   type: str
    #   version_added: "3.7"

        