- name: Add tower Organization
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Configure Organization
      tower_organization:
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "Default"
        description: ""
        # custom_virtualenv: "/var/lib/awx/venv/foo-venv/"
        state: present       

# options: #######################################################################        

#     name:
#       description:
#         - Name to use for the organization.
#       required: True
#       type: str

#     description:
#       description:
#         - The description to use for the organization.
#       type: str

#     custom_virtualenv:
#       version_added: "2.9"
#       description:
#         - Local absolute file path containing a custom Python virtualenv to use.
#       type: str
#       required: False
#       default: ''

#     max_hosts:
#       description:
#         - The max hosts allowed in this organizations
#       default: "0"
#       type: int
#       required: False
#       version_added: "3.7"

#     state:
#       description:
#         - Desired state of the resource.
#       default: "present"
#       choices: ["present", "absent"]
#       type: str

#     tower_oauthtoken:
#       description:
#         - The Tower OAuth token to use.
#       required: False
#       type: str
#       version_added: "3.7"
