- name: Add tower project
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Configure projects
      tower_project:
        tower_host: "127.0.0.1:8013"
        tower_username: "admin"
        tower_password: "coolzero"
        tower_verify_ssl: False
        name: "openstack-builder-testing"
        organization: Default
        state: present
        scm_type: git
        scm_url: "https://github.com/leifmadsen/openstack-inventory-builder.git"
        scm_branch: master
        scm_clean: yes
        #scm_credential: Git
        scm_delete_on_update: yes
        scm_update_on_launch: yes    