- name: Add tower job template
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Create tower job template
      tower_job_template:      
        # tower_host:       --> see inventory
        # tower_username:   --> see inventory
        # tower_password:   --> see inventory
        # tower_verify_ssl: --> see inventory
        # tower_oauthtoken: --> see inventory
        name: "Ping"
        # description:
        job_type: "run"
        inventory: "Local"
        project: "Demo"
        playbook: "ping.yml"
        credential: "Local"
        # credentials:
        # vault_credential:
        # forks:
        # limit:
        # verbosity:
        # extra_vars:
        # extra_vars_path:
        # job_tags:
        # force_handlers_enabled:
        # skip_tags:
        # start_at_task:
        # diff_mode_enabled:
        # fact_caching_enabled:
        # host_config_key:
        # ask_diff_mode:
        # ask_extra_vars:
        # ask_limit:
        # ask_tags:
        # ask_skip_tags:
        # ask_job_type:
        # ask_verbosity:
        # ask_inventory:
        # ask_credential:    
        # survey_enabled: yes
        # survey_spec: "{{ lookup('file', 'my_survey.json') }}"
        # become_enabled:
        # concurrent_jobs_enabled:
        # timeout:
        # custom_virtualenv: "/var/lib/awx/venv/custom-venv/"
        state: "present"

# options: #######################################################################        

    # name:
    #   description:
    #     - Name to use for the job template.
    #   required: True
    #   type: str

    # description:
    #   description:
    #     - Description to use for the job template.
    #   type: str

    # job_type:
    #   description:
    #     - The job type to use for the job template.
    #   required: False
    #   choices: ["run", "check"]
    #   type: str

    # inventory:
    #   description:
    #     - Name of the inventory to use for the job template.
    #   type: str

    # project:
    #   description:
    #     - Name of the project to use for the job template.
    #   required: True
    #   type: str

    # playbook:
    #   description:
    #     - Path to the playbook to use for the job template within the project provided.
    #   required: True
    #   type: str

    # credential:
    #   description:
    #     - Name of the credential to use for the job template.
    #     - Deprecated, mutually exclusive with 'credentials'.
    #   version_added: 2.7
    #   type: str

    # credentials:
    #   description:
    #     - List of credentials to use for the job template.
    #     - Will not remove any existing credentials. This may change in the future.
    #   version_added: 2.8
    #   type: list
    #   default: []
    #   elements: str

    # vault_credential:
    #   description:
    #     - Name of the vault credential to use for the job template.
    #     - Deprecated, mutually exclusive with 'credentials'.
    #   version_added: 2.7
    #   type: str

    # forks:
    #   description:
    #     - The number of parallel or simultaneous processes to use while executing the playbook.
    #   type: int

    # limit:
    #   description:
    #     - A host pattern to further constrain the list of hosts managed or affected by the playbook
    #   type: str

    # verbosity:
    #   description:
    #     - Control the output level Ansible produces as the playbook runs. 0 - Normal, 1 - Verbose, 2 - More Verbose, 3 - Debug, 4 - Connection Debug.
    #   choices: [0, 1, 2, 3, 4]
    #   default: 0
    #   type: int

    # extra_vars:
    #   description:
    #     - Specify C(extra_vars) for the template.
    #   type: dict
    #   version_added: 3.7

    # extra_vars_path:
    #   description:
    #     - This parameter has been deprecated, please use 'extra_vars' instead.
    #     - Path to the C(extra_vars) YAML file.
    #   type: path

    # job_tags:
    #   description:
    #     - Comma separated list of the tags to use for the job template.
    #   type: str

    # force_handlers_enabled:
    #   description:
    #     - Enable forcing playbook handlers to run even if a task fails.
    #   version_added: 2.7
    #   type: bool
    #   default: 'no'

    # skip_tags:
    #   description:
    #     - Comma separated list of the tags to skip for the job template.
    #   type: str

    # start_at_task:
    #   description:
    #     - Start the playbook at the task matching this name.
    #   version_added: 2.7
    #   type: str

    # diff_mode_enabled:
    #   description:
    #     - Enable diff mode for the job template.
    #   version_added: 2.7
    #   type: bool
    #   default: 'no'

    # fact_caching_enabled:
    #   description:
    #     - Enable use of fact caching for the job template.
    #   version_added: 2.7
    #   type: bool
    #   default: 'no'

    # host_config_key:
    #   description:
    #     - Allow provisioning callbacks using this host config key.
    #   type: str

    # ask_diff_mode:
    #   description:
    #     - Prompt user to enable diff mode (show changes) to files when supported by modules.
    #   version_added: 2.7
    #   type: bool
    #   default: 'no'

    # ask_extra_vars:
    #   description:
    #     - Prompt user for (extra_vars) on launch.
    #   type: bool
    #   default: 'no'

    # ask_limit:
    #   description:
    #     - Prompt user for a limit on launch.
    #   version_added: 2.7
    #   type: bool
    #   default: 'no'

    # ask_tags:
    #   description:
    #     - Prompt user for job tags on launch.
    #   type: bool
    #   default: 'no'

    # ask_skip_tags:
    #   description:
    #     - Prompt user for job tags to skip on launch.
    #   version_added: 2.7
    #   type: bool
    #   default: 'no'

    # ask_job_type:
    #   description:
    #     - Prompt user for job type on launch.
    #   type: bool
    #   default: 'no'

    # ask_verbosity:
    #   description:
    #     - Prompt user to choose a verbosity level on launch.
    #   version_added: 2.7
    #   type: bool
    #   default: 'no'

    # ask_inventory:
    #   description:
    #     - Prompt user for inventory on launch.
    #   type: bool
    #   default: 'no'

    # ask_credential:
    #   description:
    #     - Prompt user for credential on launch.
    #   type: bool
    #   default: 'no'

    # survey_enabled:
    #   description:
    #     - Enable a survey on the job template.
    #   version_added: 2.7
    #   type: bool
    #   default: 'no'

    # survey_spec:
    #   description:
    #     - JSON/YAML dict formatted survey definition.
    #   version_added: 2.8
    #   type: dict
    #   required: False

    # become_enabled:
    #   description:
    #     - Activate privilege escalation.
    #   type: bool
    #   default: 'no'

    # concurrent_jobs_enabled:
    #   description:
    #     - Allow simultaneous runs of the job template.
    #   version_added: 2.7
    #   type: bool
    #   default: 'no'

    # timeout:
    #   description:
    #     - Maximum time in seconds to wait for a job to finish (server-side).
    #   type: int

    # custom_virtualenv:
    #   version_added: "2.9"
    #   description:
    #     - Local absolute file path containing a custom Python virtualenv to use.
    #   type: str
    #   required: False
    #   default: ''

    # state:
    #   description:
    #     - Desired state of the resource.
    #   default: "present"
    #   choices: ["present", "absent"]
    #   type: str        