- name: Update Settings
  hosts: all
  gather_facts: false
  connection: local
  collections:
   - awx.awx
  tasks:

    # - name: Display all variables/facts known for a host
    #   debug:
    #     var: hostvars[inventory_hostname]

    # - name: Set SOCIAL_AUTH_SAML_SP_ENTITY_ID
    #   tower_settings:
    #     tower_username: "{{admin_username}}"
    #     tower_password: "{{admin_password}}"
    #     tower_host: "{{tower_url}}"
    #     tower_verify_ssl: False   
    #     ####################################
    #     name: "SOCIAL_AUTH_SAML_SP_ENTITY_ID"
    #     value: "awx.domain.nl"
    #   no_log: false

    - name: Settings * only supported by the awx module. (awx_collection)
      tower_settings:
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        settings:
          # SETTINGS -> SYSTEM:
          TOWER_URL_BASE: "https://tempdata.nl:8043"

          # SETTINGS -> AUTHENTICATION -> SAML:
          SOCIAL_AUTH_SAML_CALLBACK_URL: "https://awx.tempdata.nl/sso/complete/saml/"
          
          SOCIAL_AUTH_SAML_METADATA_URL: "https://awx.tempdata.nl/sso/metadata/saml/"
          
          SOCIAL_AUTH_SAML_SP_ENTITY_ID: "awx.tempdata.nl"
          
          # format your pem to one liner with \n
          # oneliner : awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}' cert.pem
          SOCIAL_AUTH_SAML_SP_PUBLIC_CERT: "-----BEGIN CERTIFICATE-----\nMIIDRTCCAi2gAwIBAgIJANBMS31R9MZbMA0GCSqGSIb3DQEBCwUAMDkxFDASBgNV\nBAMMC3NlY29wcy50ZWNoMRQwEgYDVQQKDAtTZWNvcHMgVGVjaDELMAkGA1UEBhMC\nVFIwHhcNMjAwMzA5MDczMDI4WhcNMjMxMjA0MDczMDI4WjA5MRQwEgYDVQQDDAtz\nZWNvcHMudGVjaDEUMBIGA1UECgwLU2Vjb3BzIFRlY2gxCzAJBgNVBAYTAlRSMIIB\nIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmYF6mtvcdfT2BkYtz19bQJ30\nE8T7HPou4fuB/play1P1ul87ZUXBbqJfKc8bCOUOlzJUG2NM0OTSGLrG5FVnygLo\nhCU0mamTx7EeV56dRyAedTDnxL6JuirsvtEr1ULuBrKj+mhvT+/ktgHAd7kjqWp9\n/vPyGurASYkpTyT+Ttv/K1zL8kiPNFLfKuZwllrlglfaIb/pBTesfkvzOFVe+Yqr\nBj5wlbj1vF82mkwETSFfR1OTuWAN1NdImMcNArmT4FOHnBkWhmKJGBx/ETi1PzQO\n3+OOriZ/cc83M865B1ek+/XgA40F7A3P3ljA6ME2leJ8mNrSCerEPujAmOi3bQID\nAQABo1AwTjAdBgNVHQ4EFgQUj9yztR+vq0115h+IwnpZ+xvnPMwwHwYDVR0jBBgw\nFoAUj9yztR+vq0115h+IwnpZ+xvnPMwwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0B\nAQsFAAOCAQEAahD3STWg0tS2ODbFQEClndmp9pRPFZb9yh1cgaDHFnV5eLtureSF\n01Fl3wTzIvhQUXAhQJ80lvA2cwK7qEeqFTfDZGjm24MOaPHwkHiJqMHepuxby65a\nHe+LgsUfYJXHeSphXh2stBhcxdCD/UyT1ASDT+VUIHJSRTqvFez7XOcReFihzAqe\nEuDJzHsxeMMynUM3bh4q58AfAk0ieZDSWFsSDnHhuGWUc4IVLVaxdj+aKf4+rOo2\nQRYFi13rhsJ5Gt6TkKykgtgRz+9B/gQbZ7DC3NGHVOT2Iq7WXqELJnF0d2PPdVB/\nUfl0TfzHQ1rhMFaVNDhZ5AuR4aSBUxnjig==\n-----END CERTIFICATE-----"
          SOCIAL_AUTH_SAML_SP_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCZgXqa29x19PYG\nRi3PX1tAnfQTxPsc+i7h+4H+mVrLU/W6XztlRcFuol8pzxsI5Q6XMlQbY0zQ5NIY\nusbkVWfKAuiEJTSZqZPHsR5Xnp1HIB51MOfEvom6Kuy+0SvVQu4GsqP6aG9P7+S2\nAcB3uSOpan3+8/Ia6sBJiSlPJP5O2/8rXMvySI80Ut8q5nCWWuWCV9ohv+kFN6x+\nS/M4VV75iqsGPnCVuPW8XzaaTARNIV9HU5O5YA3U10iYxw0CuZPgU4ecGRaGYokY\nHH8ROLU/NA7f446uJn9xzzczzrkHV6T79eADjQXsDc/eWMDowTaV4nyY2tIJ6sQ+\n6MCY6LdtAgMBAAECggEAbYZcnDFS0za8cy2Pce5vhWMtyw04viwjV0nELovspDZ7\nlUZtcoyavv1LOOF0QJxuFKLsL75iCIm6/boGPtRRAWmhzOde6GR99HUDWTDqttzL\n3oHOXCo2yoXl9R/5Tmg6vLypEvmAsmBPpy0IzmNidnZs/4O+skXcfJtIxhd2+3wR\nZQbZ5dnhVLEYwESM56cl9Wr6D4o0nnwJ5g0mQq4KiDUWPo+9xQ/lRZ0UfWMVEFhR\nlcA+OOyqkyeLHx8yIOs048phjeYE4XuJWRvV4PJQv8F2yk1acbQ9e/SqQWe57uUo\nCFpY7ntAgwl5s/PlUaWP3woMv4IMt5mHLYVGxjC9YQKBgQDInAelFeozE/x6yaWL\nNIBKqANoGz399rLfW1w/p+ilm2qoBOpmqgQwX9p8DI0PrTpNDujDJEL0m8Nnjb/K\nXlIVmI0XhJglD/pv57wRzJcCEV/6uWdbXSyvDzFaHClFkCpA09TrbToFWJ/L9A+Z\n2htsf8pX44mrcmepGhqzHhIhSwKBgQDD4/MBkBhrM2BZKPzZZv/6TsiwP685+iYm\nx59aIRwx0nR2hk91xOnt2DEE3ZechyCRSg7RJTzKCXUezkSG7D9uFJ942ZNSvan0\njF4+EkNDC2QYSmB+eqKSlcLWy8bwNcqtGCEfot8S+wBc1uV2CebSQFlWisB2YgtT\nKrF5B27PJwKBgAUYubT+/ok3q8Vu1A7aUZwT8qo1bvjByL+V8Z0IZge3EBmerlnX\nXe3gsYtPQlIwo3eLtmwmwrC2OFusJUA97zXvPz5mtvrSEhm/uG53VSrPSDH1feO7\nVURJTYatinri87/b4d/tUXkLTFwBIlhVSzcRdBGRjVDWwj1wlVcRn4JLAoGAJGNd\nqranspIynZ1disz1U/v6j7Lky/JJz/5Y/ZcU87RSagn9DLVtdv8n6+110l/Pju2g\n3vz509X56aULWbzc84flL7/K/B27SnAguYsO749YIqL+VcBWHsCvFtN3uvtjENBg\nps3Mfmwd3yEUMt8X/4pwjgDsS5Fe5S4TFZZp4RUCgYAwLTwER07o7tqelqns07Uk\nhQnZBU3YuCb0yZziR5e6zx7I8QPmzzMQ8GHBxDA66iDv1FAYA6/fJk+bOp6ep+JK\ni3V9bBBOeSGC5MJZAVUBMMmSdGoqkshTlgkpKs1+OLzdqHYPuDAFQqMXD33t5ISF\nDY22GiLq1MV/FKz8h5DqJg==\n-----END PRIVATE KEY-----"
          
          SOCIAL_AUTH_SAML_ORG_INFO:
            en-US:
              url: "https://whocares.com"
              name: "who cares it is not important"
              displayname: "This is only a name, it is not of importance"

          SOCIAL_AUTH_SAML_TECHNICAL_CONTACT:
            givenName: "aa"
            emailAddress: "your@email.com"

          SOCIAL_AUTH_SAML_SUPPORT_CONTACT:
            givenName: "aa"
            emailAddress: "your@email.com"

          SOCIAL_AUTH_SAML_ENABLED_IDPS:
            ibmcic:
              entity_id: "https://poc.ice.ibmcloud.com/saml/sps/saml20ip/saml20"
              url: "https://poc.ice.ibmcloud.com/saml/sps/saml20ip/saml20/login"
              attr_email: "userID"
              attr_first_name: "given_name"
              attr_last_name: "family_name"
              attr_user_permanent_id: "userID"
              attr_username: "preferred_username"
              x509cert: "MIIDKDCCAhCgAwIBAgIECPYTzTANBgkqhkiG9w0BAQsFADBWMQkwBwYDVQQGEwAxCTAHBgNVBAgTADEJMAcGA1UEBxMAMQkwBwYDVQQKEwAxCTAHBgNVBAsTADEdMBsGA1UEAxMUcG9jLmljZS5pYm1jbG91ZC5jb20wHhcNMTkxMTI1MDkxMDIyWhcNMjkxMTIyMDkxMDIyWjBWMQkwBwYDVQQGEwAxCTAHBgNVBAgTADEJMAcGA1UEBxMAMQkwBwYDVQQKEwAxCTAHBgNVBAsTADEdMBsGA1UEAxMUcG9jLmljZS5pYm1jbG91ZC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCK6a7G64+9vzf0MuTaMR/5VBvrWGYF38v2iYEW4tyz6dkdu0aJQ2qocwHd3aTdY8PzuBFcpCN8CvVY3/7mSZMhoMUZV5/g81XpwGnqOpczS17A6MYvCeXbZarjaT7UayopXQXqaNeo0BVsyZF9eFRRAIWA5JB9q/FMM2FeLFFAwdNTCsslPy8zFusLH7Pslgu1/rjzAyjHRB5WAPzKZTAyNO654isC2/uz7H+fMLnU7VPFk5S14qk7Qo4xaloXIRkctYdhrC2J8NG7YXEnidYMwGat3iIa7c5F1IicQcXJTnY2glr7xM3K0r6MfdgwBmEmgkDpkNbbGXijDhSpyqUDAgMBAAEwDQYJKoZIhvcNAQELBQADggEBAEpFlgmJ7NjY0OTRYmXOLC4qMOX1Z3TnJ9Q2vsFPs80rphzd/k1IoapE5/5E+p/OJp6ruksbp8SgzPK/wTQxAunWUrzBvcgbIDnKhX5AimfQUFzRd4332N7M/lewdiM+5nQJIImNPYZY0MFpV4pSwae0hc4KRaSvq3L3/QAitNb6XPRx6K3f2phZJkTudbL2AePcymDufWST708Uex4UzoN0EkP3uQIGG/K8nxXVdEwFgCFPWSqu6VE3IxMxPwOAuUfolZ9WWarFU0q/2F3pUBSGW0PuDGCmKa+8Ie5sqkj8p9GlWq9mmG0J8gpFnYXpoM0nr+GNA6KMfmBx8Iox8jU="

          SOCIAL_AUTH_SAML_ORGANIZATION_MAP: 

          SOCIAL_AUTH_SAML_ORGANIZATION_ATTR: 
          
          SOCIAL_AUTH_SAML_TEAM_MAP: 
          
          # need PR: https://github.com/ansible/awx/pull/6076
          SOCIAL_AUTH_SAML_TEAM_ATTR:
            team_org_map: [{
              "team": "awx-members",
              "organization": "awx-members"
            }, {
              "admins": true,
              "team": "awx-admins",
              "organization": "awx-admins"
            }, {
              "auditors": true,
              "team": "awx-auditors",
              "organization": "awx-auditors"
            }, {
              "superusers": true,
              "team": "awx-superusers",
              "organization": "awx-superusers"
            }]
            saml_attr: "groupIds"
            remove: true
            admins_remove: true
            auditors_remove: true
            superusers_remove: true

          SOCIAL_AUTH_SAML_SECURITY_CONFIG:
            requestedAuthnContext: false

          SOCIAL_AUTH_SAML_SP_EXTRA:
          
          SOCIAL_AUTH_SAML_EXTRA_DATA:

# options: #######################################################################        

    # name:
    #   description:
    #     - Name of setting to modify
    #   required: False
    #   type: str

    # value:
    #   description:
    #     - Value to be modified for given setting.
    #   required: False
    #   type: str
    
    # settings:
    #   description:
    #     - A data structure to be sent into the settings endpoint
    #   required: False
    #   type: dict
    #   version_added: "3.7"
    
    # tower_oauthtoken:
    #   description:
    #     - The Tower OAuth token to use.
    #   required: False
    #   type: str
    #   version_added: "3.7"

        