
- name: AWX - Update Settings. 
  hosts: all
  no_log: False
  connection: local
  gather_facts: no
  vars:
    log_level: "DEBUG"
  roles:
    - role: start_awx_config

    #############################################################################################################################################################################

    # One Liner Certificate into one string: awk 'NF {sub(/\r/, ""); printf "%s\\n",$0;}' cert.crt

    # AWX Update Settings
    - role: awx_update_settings
      SOCIAL_AUTH_SAML_CALLBACK_URL: "https://awx.domain.nl/sso/complete/saml/"
      SOCIAL_AUTH_SAML_METADATA_URL: "https://awx.domain.nl/sso/metadata/saml/"
      SOCIAL_AUTH_SAML_SP_ENTITY_ID: "awx.domain.nl"
      SOCIAL_AUTH_SAML_SP_PUBLIC_CERT: "-----BEGIN CERTIFICATE-----\nMIIDRTCCAi2gAwIBAgIJAIC8KS2n8a7DMA0GCSqGSIb3DQEBCwUAMDkxFDASBgNV\n-----END CERTIFICATE-----"
      SOCIAL_AUTH_SAML_SP_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDAwBtAy9IBYhEs\n-----END PRIVATE KEY-----"
      SOCIAL_AUTH_SAML_ORG_INFO: |
        {
          "en-US": {
          "url": "https://whocares.com",
          "name": "who cares it is not important",
          "displayname": "This is only a name, it is not of importance"
          }
        }
      SOCIAL_AUTH_SAML_TECHNICAL_CONTACT: |
        {
        "givenName": "your name",
        "emailAddress": "your@email.com"
        }
      SOCIAL_AUTH_SAML_SUPPORT_CONTACT: |
        {
        "givenName": "your name",
        "emailAddress": "your@email.com"
        }      
      SOCIAL_AUTH_SAML_ENABLED_IDPS: |
        {
          "ibmcic": {
           "entity_id": "https://yourtenant.ice.ibmcloud.com/saml/sps/saml20ip/saml20",
           "url": "https://yourtenant.ice.ibmcloud.com/saml/sps/saml20ip/saml20/login",
           "attr_email": "userID",
           "attr_first_name": "given_name",
           "attr_last_name": "family_name",
           "attr_user_permanent_id": "userID",
           "attr_username": "preferred_username",
           "x509cert": "MIIDKDCCAhCgAwIBAgIECPYTzTANBgkqhkiG9w0BAQs...."
          }
        }      
      SOCIAL_AUTH_SAML_ORGANIZATION_MAP: ""
      SOCIAL_AUTH_SAML_ORGANIZATION_ATTR: ""
      SOCIAL_AUTH_SAML_TEAM_MAP: ""
      SOCIAL_AUTH_SAML_TEAM_ATTR: |
        {
          "saml_attr": "groupIds",
            "team_org_map": [{
              "team": "awx-members",
              "organization": "awx-members"
            }, {
              "admins": true,
              "team": "awx-admins",
              "organization": "awx-admins"
            }, {
              "auditors": true,
              "team": "awx-auditors",
              "organization": "awx-auditors"
            }, {
              "superusers": true,
              "team": "awx-superusers",
              "organization": "awx-superusers"
            }],
          "remove": true,
          "admins_remove": true,
          "auditors_remove": true,
          "superusers_remove": true
        }
      SOCIAL_AUTH_SAML_SECURITY_CONFIG: |
        {
          "requestedAuthnContext": false
        }
      SOCIAL_AUTH_SAML_SP_EXTRA: ""
      SOCIAL_AUTH_SAML_EXTRA_DATA: ""
