
# - name: AWX - Add Project. 
#   hosts: all
#   no_log: False
#   connection: local
#   gather_facts: no
#   vars:
#     log_level: "DEBUG"
#   roles:
#     - role: start_awx_config

    #############################################################################################################################################################################

    # AWX Update Settings
    # - role: awx_add_project
    #   name: "ibmsecurity_ci (master)"
    #   organization: "1"   # 1 = default
    #   description: ""
    #   scm_type: "git"                     # git / hg / svn / 
    #   base_dir: "/var/lib/awx/projects/"
    #   scm_url: "https://github.com/CoolZeroNL/ibmsecurity_ci.git"
    #   scm_branch: ""
    #   scm_refspec: ""
    #   scm_clean: True                     # True / False
    #   scm_delete_on_update: True          # True / False
    #   scm_update_on_launch: False         # True / False
    #   allow_override: False               # True / False
    #   scm_update_cache_timeout: "0"
    #   custom_virtualenv: "null"

- name: Add tower project
  tower_project:
    name: "ibmsecurity_ci (master)"
    description: ""
    organization: "default"
    scm_type: "git"                     # git / hg / svn / 
    scm_url: "https://github.com/CoolZeroNL/ibmsecurity_ci.git"
    state: present
    # tower_config_file: "~/tower_cli.cfg"
    
# - name: Add Tower Project with cache timeout and custom virtualenv
#   tower_project:
#     name: "Foo"
#     description: "Foo bar project"
#     organization: "test"
#     scm_update_on_launch: True
#     scm_update_cache_timeout: 60
#     custom_virtualenv: "/var/lib/awx/venv/ansible-2.2"
#     state: present
#     tower_config_file: "~/tower_cli.cfg"