- name: Add an inventory source
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Configure inventory source
      tower_inventory_source:     
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "localhost"
        # new_name:
        description: "awx localhost inventory"
        inventory: "AWX-localhost"
        source: "scm"
        source_project: "ibmsecurity_ci (master)"
        source_path: "awx-ansible-inventories/inventories/localhost/hosts"
        # source_script:
        # source_vars:
          # private: false
        # credential: previously-created-credential
        # source_regions:
        # instance_filters:
        # group_by:
        overwrite: True                     # True / False # If checked, any hosts and groups that were previously present on the external source but are now removed will be removed from the Tower inventory. Hosts and groups that were not managed by the inventory source will be promoted to the next manually created group or if there is no manually created group to promote them into, they will be left in the "all" default group for the inventory. When not checked, local child hosts and groups not found on the external source will remain untouched by the inventory update process.
        overwrite_vars: True                # True / False # If checked, all variables for child groups and hosts will be removed and replaced by those found on the external source. When not checked, a merge will be performed, combining local variables with those found on the external source.
        update_on_launch: True              # True / False # Each time a job runs using this inventory, refresh the inventory from the selected source before executing job tasks.
        update_on_project_update: False     # True / False # After every project update where the SCM revision changes, refresh the inventory from the selected source before executing job tasks. This is intended for static content, like the Ansible inventory .ini file format
        # custom_virtualenv:
        # timeout:
        # update_cache_timeout:
        # state:

    - name: Configure inventory source
      tower_inventory_source:     
        tower_username: "{{admin_username}}"
        tower_password: "{{admin_password}}"
        tower_host: "{{tower_url}}"
        tower_verify_ssl: False   
        ####################################
        name: "localhost"
        # new_name:
        description: ""
        inventory: "Multi-Brand"
        source: "scm"
        source_project: "ibmsecurity_ci (master)"
        source_path: "demo-ansible-inventories/inventories/multible_brands/hosts"
        overwrite: True                     # True / False # If checked, any hosts and groups that were previously present on the external source but are now removed will be removed from the Tower inventory. Hosts and groups that were not managed by the inventory source will be promoted to the next manually created group or if there is no manually created group to promote them into, they will be left in the "all" default group for the inventory. When not checked, local child hosts and groups not found on the external source will remain untouched by the inventory update process.
        overwrite_vars: True                # True / False # If checked, all variables for child groups and hosts will be removed and replaced by those found on the external source. When not checked, a merge will be performed, combining local variables with those found on the external source.
        update_on_launch: False              # True / False # Each time a job runs using this inventory, refresh the inventory from the selected source before executing job tasks.
        update_on_project_update: True     # True / False # After every project update where the SCM revision changes, refresh the inventory from the selected source before executing job tasks. This is intended for static content, like the Ansible inventory .ini file format
        
# options: #######################################################################        
# name:
#   description:
#     - The name to use for the inventory source.
#   required: True
#   type: str

# new_name:
#   description:
#     - A new name for this assets (will rename the asset)
#   required: False
#   type: str
#   version_added: "3.7"

# description:
#   description:
#     - The description to use for the inventory source.
#   type: str

# inventory:
#   description:
#     - Inventory the group should be made a member of.
#   required: True
#   type: str

# source:
#   description:
#     - The source to use for this group.
#   choices: [ "scm", "ec2", "gce", "azure_rm", "vmware", "satellite6", "cloudforms", "openstack", "rhv", "tower", "custom" ]
#   type: str
#   required: False

# source_path:
#   description:
#     - For an SCM based inventory source, the source path points to the file within the repo to use as an inventory.
#   type: str

# source_script:
#   description:
#     - Inventory script to be used when group type is C(custom).
#   type: str
#   required: False

# source_vars:
#   description:
#     - The variables or environment fields to apply to this source type.
#   type: dict

# credential:
#   description:
#     - Credential to use for the source.
#   type: str

# source_regions:
#   description:
#     - Regions for cloud provider.
#   type: str

# instance_filters:
#   description:
#     - Comma-separated list of filter expressions for matching hosts.
#   type: str

# group_by:
#   description:
#     - Limit groups automatically created from inventory source.
#   type: str

# overwrite:
#   description:
#     - Delete child groups and hosts not found in source.
#   type: bool
#   default: 'no'

# overwrite_vars:
#   description:
#     - Override vars in child groups and hosts with those from external source.
#   type: bool

# custom_virtualenv:
#   version_added: "2.9"
#   description:
#     - Local absolute file path containing a custom Python virtualenv to use.
#   type: str
#   required: False
#   default: ''

# timeout:
#   description: The amount of time (in seconds) to run before the task is canceled.
#   type: int
# verbosity:
#   description: The verbosity level to run this inventory source under.
#   type: int
#   choices: [ 0, 1, 2 ]

# update_on_launch:
#   description:
#     - Refresh inventory data from its source each time a job is run.
#   type: bool
#   default: 'no'

# update_cache_timeout:
#   description:
#     - Time in seconds to consider an inventory sync to be current.
#   type: int

# source_project:
#   description:
#     - Project to use as source with scm option
#   type: str

# update_on_project_update:
#   description: Update this source when the related project updates if source is C(scm)
#   type: bool

# state:
#   description:
#     - Desired state of the resource.
#   default: "present"
#   choices: ["present", "absent"]
#   type: str

# tower_oauthtoken:
#   description:
#     - The Tower OAuth token to use.
#   required: False
#   type: str
#   version_added: "3.7"