
- name: AWX - Add Inventory. 
  hosts: all
  no_log: False
  connection: local
  gather_facts: no
  vars:
    log_level: "DEBUG"
  roles:
    - role: start_awx_config

    #############################################################################################################################################################################

    # AWX Update Settings
    - role: awx_add_inventory
      name: "AWX - Localhost"
      organization: "1"   # 1 = default
      variables: "---"