- name: Playbook - Install / update AWX (Python Collections). 
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - pip:
      name: ansible-tower-cli

    - name: multiline shell command
      shell: |
        # pip3 install --user ansible-tower-cli
        # /usr/local/lib/python3.6/site-packages


        # ansible-galaxy collection install awx.awx

        # install for AWX Tower.
        if [ -d /usr/lib/python3.6/site-packages/ansible/ ] 
        then
          PYPATH='/usr/lib/python3.6/site-packages'
        fi

        if [ -d /usr/local/lib/python3.6/site-packages/ansible/ ] 
        then
          PYPATH='/usr/local/lib/python3.6/site-packages'          
        fi

        echo $PYPATH

        # git clone https://github.com/ansible/awx.git
        # cd awx
        # cp -R awx_collection /var/lib/awx/.ansible/collections/
        
        # cd awx/awx_collection/plugins
        
        # cp modules/* $PYPATH/ansible/modules/web_infrastructure/ansible_tower/
        # cp module_utils/* $PYPATH/ansible/module_utils/
        # cp doc_fragments/* $PYPATH/ansible/plugins/doc_fragments
        # cp inventory/* $PYPATH/ansible/plugins/inventory  
    
        # Housecleaning
        # rm -R awx

      register: stdout

    - name: debug output
      debug: msg={{ stdout }}