- name: Playbook - Install / update AWX (Python Collections). 
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: multiline shell command
      shell: |
        # install for AWX Tower.
        if [ -d /usr/lib/python3.6/site-packages/ansible/ ] 
        then
          PYPATH='/usr/lib/python3.6/site-packages'
        fi

        if [ -d /usr/local/lib/python3.6/site-packages/ansible/ ] 
        then
          PYPATH='/usr/local/lib/python3.6/site-packages'          
        fi

        echo $PYPATH

        pip3 install --target=$PYPATH rsa
        pip3 install --target=$PYPATH wheel==0.30.0
        pip3 install --target=$PYPATH ansible-tower-cli

        # delete current tower_* modules
        if [ -d /usr/lib/python3.6/site-packages/ansible/modules/web_infrastructure/ansible_tower/ ] 
        then
          rm -R /usr/lib/python3.6/site-packages/ansible/modules/web_infrastructure/ansible_tower/
        fi
        
        cd /tmp
        git clone https://github.com/ansible/awx.git
        cd awx/awx_collection/plugins
        
        cp modules/* $PYPATH/ansible/modules/
        cp module_utils/* $PYPATH/ansible/module_utils/
        cp doc_fragments/* $PYPATH/ansible/plugins/doc_fragments
        cp inventory/* $PYPATH/ansible/inventory  

        # Housecleaning
        cd /tmp
        rm -R awx

      register: stdout

    - name: debug output
      debug: msg={{ stdout }}