- name: Playbook - Install / update IBM Security Toolkit (Python Modules). 
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: multiline shell command
      shell: |
        pip3 install ansible-tower-cli

        # awx_collection
        git clone https://github.com/ansible/awx.git
        cd awx
        cp -R awx_collection /var/lib/awx/.ansible/collections/
  
        # Housecleaning
        rm -R awx

        # ansible-galaxy collection install awx.awx

      register: stdout

    - name: debug output
      debug: msg={{ stdout }}