- name: Add tower project
  hosts: all
  gather_facts: false
  connection: local
  tower_project:
    name: "ibmsecurity_ci (master)"
    description: ""
    organization: "default"
    scm_type: "git"                     # git / hg / svn / 
    scm_url: "https://github.com/CoolZeroNL/ibmsecurity_ci.git"
    state: present
    # tower_config_file: "~/tower_cli.cfg"