- name: Delete a applications.
  ci:
    appliance:      "{{ inventory_hostname }}"
    client_id:      "{{ client_id }}"
    client_secret:  "{{ client_secret }}"
    lmi_port:       "{{ lmi_port }}"
    log:            "{{ log_level }}"
    force:          "{{ force }}"
    ciapi:
      appname:      "{{ appname }}"    
    action: ibmsecurity.ci.applications.delete
