- name: Creates a group in IBM Cloud Identity Cloud Directory. 
  ci:
    appliance:      "{{ inventory_hostname }}"
    client_id:      "{{ client_id }}"
    client_secret:  "{{ client_secret }}"
    lmi_port:       "{{ lmi_port }}"
    log:            "{{ log_level }}"
    force:          "{{ force }}"
    header:         "application/scim+json"
    ciapi:
      displayname:  "{{ displayname }}"
      description:  "{{ description }}"
    action: ibmsecurity.ci.groups.add

