
- name: add certificates.
  hosts: all
  no_log: False
  connection: local
  gather_facts: no
  vars:
    log_level: "DEBUG"
  roles:
    - role: start_ci_config

    # format your pem to one liner with \n, and a \ for ignoring the \ in yml.
    # oneliner : awk 'NF {sub(/\r/, ""); printf "%s\\\\n",$0;}' 1571753451.pem

    # use `pemcertfile` or `pemcert`
    - role: add_signercert
      pemcertfile: "filename.pem"
      pemcert: ""
      label: "1234"
      
    # use `p12certfile` or `p12cert`.
    - role: add_personalcert
      p12certfile: "filename.p12"     # path + filename of p12
      p12cert: ""                     # base64 encoded p12
      isdefault: False
      password: "password"
      label: "testlabel"
    