- name: Add a Attribute. 
  hosts: "{{ hosts | default('all') }}"
  no_log: False
  connection: local
  gather_facts: no
  vars:
    log_level: "DEBUG"
  roles:
    - role: start_ci_config

    # - role: delete_attribute
    #   attributename: "testname1"

    # Custom Attribute ############################################################################################################################################################################

    - role: add_attribute

    # Name and Description
      attributename: "testname1"     
      # new_attributename: ""     
      attributedescription: "desc"

    # Type and availability
      sourcetype: "schema"
        # schema      == Create a custom user profile attribute.
        # credential  == Add an attribute sent from any of your connected identity sources during login.
        # static      == Static value that applies to all users.

    # Attributes can be used for multiple purposes. Set the purposes you want this attribute to be available for.
    # Make available for (select all that apply)
      singlesignon: "sso"       
        # sso == checkbox checked. 
        # empty = checkbox not checked.

    # Source and value
      attributeidentifier: "Attributeidentifier"                  # The attribute identifier cannot contain spaces, periods, hyphens, or underscores.
      datatype: "string"                                          # The expected format of this value
        # string    == String
        # string[]  == Multivalue String
        # number    == Number
        # boolean   == Boolean

    # Enter the attribute name from each identity source you want to map to this attribute. If the identity source does not provide the attribute, the value from Cloud Directory is used.
    # if identitysource == empty then this attribute is for all identity source
      identitysource: "www.facebook.com"                          # domain of the Identity Source: FB = www.facebook.com, IBMid = www.ibm.com, empty = al identity source
      attributenamefromtheidentitysource: "1"                     # 

    # View additional settings
      defaultvalue: "defaultvalue"                                # Default value to be used if no value can be determined.
      
      applytransformation: "base64Decode"                         # Transform the value of the attribute
        #                     == None
        # base64Decode        == Base64 Decode
        # base64Encode        == Base64 Encode
        # decodeURI           == Decode URI
        # decodeURIComponent  == Decode URI Component
        # encodeURI           == Encode URI
        # encodeURIComponent  == Encode URI Component
        # generateUuidIfNull  == Generate UUID if no value is found
        # lowercase           == Lowercase
        # uppercase           == Uppercase

      scope: "tenant"
