
- name: Add a Idenity Source.
  hosts: "{{ hosts | default('all') }}"
  no_log: False
  connection: local
  gather_facts: no
  vars:
    log_level: "DEBUG"
  roles:
    - role: start_ci_config
    - role: add_identitysource

    # - role: add_identitysource
    #   sourcetypeid: "5"
    #   instancename: "Cloud Directory"      
    #   enabled: true
    #   # # Cloud Directory
    #   properties:
    #     - passwordResetEnabled:
    #         sensitive: false
    #         value: "false"

