
- name: Add entitlements to Application. 
  hosts: all
  no_log: False
  connection: local
  gather_facts: no
  vars:
    log_level: "DEBUG"
  roles:
    - role: start_ci_config
    - role: add_application_entitlements
      appid: ""
      birthrightaccess: true