
- name: Get Group Filter
  hosts: "{{ hosts | default('all') }}"
  no_log: False
  connection: local
  gather_facts: no
  vars:
    log_level: "DEBUG"
  roles:
    - role: start_ci_config
    
    - role: get_group_filter
      filter: 'displayName eq \"Sales\"'