- name: Gets the list of all Idenity Sources.
  hosts: all
  no_log: False
  connection: local
  gather_facts: no
  vars:
    log_level: "DEBUG"
  roles:
    - role: start_ci_config
    
    - role: get_all_identitysources
