
- name: Playbook - Install / update IBM Security Toolkit (Python Modules). 
  hosts: "{{ hosts | default('all') }}"
  gather_facts: false
  connection: local
  tasks:
    - name: multiline shell command
      shell: |
        # Install IBMSecurity Python Modules
        # pip3 install --user --upgrade git+https://github.com/ibm-security/ibmsecurity#egg=ibmsecurity
        # pip3 install --upgrade git+https://github.com/ibm-security/ibmsecurity#egg=ibmsecurity

        # Clone IBM Python Modules
        git clone https://github.com/ibm-security/ibmsecurity.git
        cd ibmsecurity
        cp -R ibmsecurity /usr/local/lib/python3.6/site-packages

        # Clone CIC Python Modules
        git clone https://github.com/CoolZeroNL/ibmsecurity_ci.git
        
        # Copy them to the right location.
        cd ibmsecurity_ci/
        # cp -R ibmsecurity /var/lib/awx/.local/lib/python3.6/site-packages/
        cp -R ibmsecurity /usr/local/lib/python3.6/site-packages

        # back, and cleanup.
        # cd ..
        # rm -R ibmsecurity_ci

      register: stdout

    - name: debug output
      debug: msg={{ stdout }}