- name: Update PasswordPolicies
  hosts: "{{ hosts | default('all') }}"
  no_log: False
  connection: local
  gather_facts: no
  vars:
    log_level: "DEBUG"
  roles:
    - role: start_ci_config

    - role: update_passwordpolicies
      schemas: "urn:ietf:params:scim:schemas:ibm:core:2.0:policy:Password"      # Cloud Directory
      properties:    
        # Generic 
        - pwdExpireWarning: "0"

        # Password Strength
        - pwdMinLength: "8"            # Enforce password minimum length to [nn] characters
        - passwordMinAlphaChars: "0"   # Require a minimum of [nn] alphabetic characters            0 = Disable				
        - passwordMinOtherChars: "0"   # Require a minimum of [nn] numeric and special characters   0 = Disable

        # Password Security
        - pwdMinAge: "0"               # Set minimum password age to [nn] hours                     0 = Disable
        - pwdInHistory: "0"            # Disallow reuse of the last [nn] passwords                  0 = Disable
        - pwdLockout: false            # true = enable / false = disable
        - pwdLockoutDuration: "1"      # Lock accounts for [nn] minutes
        - pwdMaxFailure: "1"           # after [nn] failed logins.

        # Is been call in background in the GUI, Dont know for what. And are not required.
        # - pwdGraceLoginLimit: "0"
        # - pwdMustChange: true
        # - pwdMaxAge: "0"
        # - pwdAllowUserChange: true
        # - passwordMinOtherChars: "1"
        # - pwdFailureCountInterval: "0"
        # - passwordMaxRepeatedChars: "0"
        # - pwdSafeModify: false
        # - passwordMaxConsecutiveRepeatedChars: "0"
        # - passwordMinDiffChars: "0"
        # - ibm_pwdPolicy: true
        # - pwdCheckSyntax: "1"

 
  