
- name: Upload templates (complete zip)
  hosts: "{{ hosts | default('all') }}"
  no_log: False
  connection: local
  gather_facts: no
  vars:
    log_level: "DEBUG"
  roles:
    - role: start_ci_config

    - role: upload_customization_zip
      file: "templates.zip"
    