- name: AWX - Add Template. 
  awx:
    appliance:      "{{ inventory_hostname }}"
    awx_user:       "{{ awx_user }}"
    awx_password:   "{{ awx_password }}"
    lmi_port:       "{{ lmi_port }}"
    log:            "{{ log_level }}"
    force:          "{{ force }}"
    # header:       "application/json"
    awxapi:
      name:                     "{{ name }}"
      job_type:                 "{{ job_type }}"
      inventory:                "{{ inventory }}"
      project:                  "{{ project }}"
      playbook:                 "{{ playbook }}"
      verbosity:                "{{ verbosity }}"    
      description:              "{{ description | default(None) }}"
      job_tags:                 "{{ job_tags | default(None) }}"
      skip_tags:                "{{ skip_tags | default(None) }}"
      custom_virtualenv:        "{{ custom_virtualenv | default(None) }}"
      job_slice_count:          "{{ job_slice_count | default(None) }}"
      timeout:                  "{{ timeout | default(None) }}"
      become_enabled:           "{{ become_enabled | default(None) }}"
      allow_callbacks:          "{{ allow_callbacks | default(None) }}"
      enable_webhook:           "{{ enable_webhook | default(None) }}"
      allow_simultaneous:       "{{ allow_simultaneous | default(None) }}"
      use_fact_cache:           "{{ use_fact_cache | default(None) }}"
      host_config_key:          "{{ host_config_key | default(None) }}"
      ebhook_credential:        "{{ ebhook_credential | default(None) }}"
      forks:                    "{{ forks | default(None) }}"
      ask_diff_mode_on_launch:  "{{ ask_diff_mode_on_launch | default(None) }}"
      ask_scm_branch_on_launch: "{{ ask_scm_branch_on_launch | default(None) }}"
      ask_tags_on_launch:       "{{ ask_tags_on_launch | default(None) }}"
      ask_skip_tags_on_launch:  "{{ ask_skip_tags_on_launch | default(None) }}"
      ask_limit_on_launch:      "{{ ask_limit_on_launch | default(None) }}"
      ask_job_type_on_launch:   "{{ ask_job_type_on_launch | default(None) }}"
      ask_verbosity_on_launch:  "{{ ask_verbosity_on_launch | default(None) }}"
      ask_inventory_on_launch:  "{{ ask_inventory_on_launch | default(None) }}"
      ask_variables_on_launch:  "{{ ask_variables_on_launch | default(None) }}"
      ask_credential_on_launch: "{{ ask_credential_on_launch | default(None) }}"
      extra_vars:               "{{ extra_vars | default(None) }}"
      survey_enabled:           "{{ survey_enabled | default(None) }}"
    action: ibmsecurity.awx.templates.add


